routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', function () {
    return view('auth.login');
});


//Route::get('/home', 'NewsController@index')->name('home');
Route::get('/news/pagination','NewsController@pagination');
Route::get('/news/search/{search}','NewsController@search')->name('news.search');
Route::get('/news/deleted','NewsController@deleted')->name('news.deleted');
Route::get('/news/restore/{id}','NewsController@restore')->name('news.restore');
Route::get('/news/deleted/search/{search}','NewsController@search_del')->name('news.searchdel');
Route::resource('news', 'NewsController');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class News extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at','created_at','updated_at'];
    protected $table="news";
    public $primaryKey="id";
    public $timestamps=true;

    public function user(){
        return $this->hasOne('App\User','id','id_user');
    }

    public function state(){
        return $this->hasOne('App\States','id','id_state');
    }

    //FUNCOES DE MODELO
    
    
    public function scopeGetAllNews($query,bool $trashed=null,bool $isajax=null):Object{
        //Necessário dar Join porque Ajax nao acede às collections criadas pelo laravel
        if($isajax){
            $query->select("news.id","title","name as publisher","description as state","news.created_at","news.deleted_at")
            ->join('users','id_user','users.id')
            ->join('states','id_state','states.id');
        }
        if($trashed){ 
             $query->onlyTrashed();
        }
            return $query->orderBy('created_at','desc')->paginate(5);
       
    }

    /**
     * Guardar Dados de Artigos
     * @param $data - Dados para armazenar do artigo
     * @param $id - id do artigo.Se vier nulo é um artigo novo.Outrora o artigo com esse id será atualizado
     */
    public function scopestoreArticle($query,array $data,int $id=null):bool{
        if($id){
            $query->where('news.id',$id);
            return  $query->update($data);
        }
        else{
            return $query->insert($data);
        }      
    }
    
    /**
     * Buscar artigo X
     * @param $id - Id do artigo a buscar.
     * Inclui trashed para os admins poderem visualizar o artigo na mesma.
     * Retirar esse parametro para os utilizadores normais
     */
    public function scopegetArticle($query,int $id):Object{
        return $query->withTrashed()->where('news.id',$id)->first();
        
    }

    /**
     * Destruir Artigo X
     * @param $id - Id do artigo a eliminar
     * 
     * Destroi o artigo.Como usamos a opcao de SoftDelete,o sistema do laravel
     * oculta todos os resultados das queries a nao ser que use-se a funcao withTrashed() ou onlyTrashed()
     * Restore retira o artigo dos eliminados
     */
    public function scopedestroyArticle($query,int $id):bool{
       return $query->where('news.id',$id)->delete();
    }


    /**
     * Restaura Artigo X
     * @param $id - Id do artigo a Restaurar
     * 
     * Restaura um artigo anteriormente apagado
     */
    public function scoperestoreArticle($query,int $id):bool{
        return $query->onlyTrashed()->where('news.id',$id)->restore();
    }

    /**
     * Pesquisa
     * @param $data - Array com  os parametros de pesquisa.
     *  Se é uma pesquisa AJAX terá um index adicional no array indicando.
     */
    public function scopesearchNews($query,array $data):Object{       
        $order="DESC";
        //Necessário dar Join porque Ajax nao acede às collections criadas pelo laravel
        if(isset($data['isajx']) && $data['isajx']===1){
         $query->select("news.id","title","name as publisher","description as state","news.created_at","news.deleted_at")
         ->join('users','id_user','users.id')
         ->join('states','id_state','states.id');
        }

        if($data['id_state']){
            $query=$query->where('id_state',$data['id_state']);
        }
        if($data['created_at']){
            $query=$query->whereDate('news.created_at', '=',$data['created_at']); # >= para incluir artigos a partir de X dia
            $order="ASC";
        }

        if($data['title']){
            $query=$query->where('title','like','%'.$data['title'].'%');
        }

        if($data['trashed']==1){
            $query=$query->onlyTrashed();
        }
        elseif($data['trashed']==2){
            $query=$query->withTrashed();
        }

        $query=$query->orderBy('created_at',$order);
        $query=$query->paginate(5);
        return $query;
        }
    }

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;
use App\States;
use App\User;
use App\News;
use Illuminate\Http\Request;

class NewsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Carrega as Noticias.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //Se for um pedido Ajax retorna o Objeto
        if($request->ajax()){

            /*as funcoes usadas tiveram que ser modificadas,pois o ajax não reconhece a collection que o laravel
            gera quando existe uma relação.Por exemplo: fazer get de uma noticia, posso logo ir buscar o nome de quem criou.
            Pelo ajax é necessário dar join das tabelas. */

            return News::GetAllNews(null,true); //(isTrashed,IsAjax)
        }
        else{
            $news=News::GetAllNews();
            $states=States::All();
            $news->title="Artigos";
            return view('home',compact('news'),compact('states'));
        }
    }

    
    public function deleted(Request $request){
        if($request->ajax()){
            return News::GetAllNews(true,true);
        }
        else{
            $news=News::GetAllNews(1);
            $states=States::All();
            $news->title="Artigos Apagados";
            return view('home',compact('news'),compact('states'));
    }
}

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $states=States::All();
        return view('news.create',compact('states'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        $this->validate($request,[
            'title'=>'required|min:3|max:50',
            'content'=>'required|max:200|min:20',
            'state'=>'required|integer',
        ]);

        $data=[
            "id"=>NULL,
            "title"=>$request->input('title'),
            "content"=>$request->input('content'),
            "id_user"=>auth()->user()->id,
            "id_state"=>$request->input('state'),
            "created_at" =>  \Carbon\Carbon::now(),
            "updated_at" => \Carbon\Carbon::now(),
        ];

        if(News::storeArticle($data)){
            if($request->ajax()){
                return json_encode([
                    'msg'=>'Noticia Criada Com Sucesso',
                    'status'=>'SUCCESS'
                ]);
            }else{
                return redirect('/news')->with('flash-success','Noticia Criada com Sucesso');
            }
        }else{
            if($request->ajax()){
                return json_encode([
                    'msg'=>'Erro ao Criar Com Sucesso',
                    'status'=>'ERROR'
                ]);
            }else{
                return redirect('/news')->with('flash-error','Erro ao criar Noticia');
            }
        }
            
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $article=News::getArticle($id);
        return view('news.show',compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $states=States::All();
        $article=News::getArticle($id);
        return view('news.edit',compact('article'),compact('states'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
            $this->validate($request,[
                'title'=>'required|min:3|max:50',
                'content'=>'required|max:200|min:20',
                'state'=>'required|integer',
            ]);

            $data=[
                "title"=>$request->input('title'),
                "content"=>$request->input('content'),
                "id_state"=>$request->input('state'),
                "updated_at" => \Carbon\Carbon::now()
            ];

            if(News::storeArticle($data,$id)){
            if($request->ajax()){
                return json_encode([
                    'msg'=>'Noticia Atualizada Com Sucesso',
                    'status'=>'SUCCESS'
                ]);
            }else{
                return redirect('/news')->with('flash-success','Noticia Atualizada com Sucesso');
                }
            }else{
                if($request->ajax()){
                return json_encode([
                    'msg'=>'Erro ao Atualizar  Noticia',
                    'status'=>'ERROR'
                ]);
            }
            else{
                return redirect('/news')->with('flash-error','Erro ao Atualizar Noticia');  
            }
                
        }
    }


    function pagination(Request $request)
    {
        if($request->ajax()){
            $data = News::All()->paginate(5);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
     
        if(News::destroyArticle($id)){
            if($request->ajax()){
                return json_encode([
                    'msg'=>'Noticia Apagada Com Sucesso',
                    'status'=>'SUCCESS'
                ]);
            }
            else{
                return redirect('/news')->with('flash-success','Noticia Apagada com Sucesso');
            }
        }   
        else{
            if($request->ajax()){
                return json_encode([
                    'msg'=>'Ocorreu um erro ao tentar apagar a notícia',
                    'status'=>'ERROR'
                ]);
            }
            else{
                return redirect('/news')->with('flash-error','Erro ao tentar apagar Noticia');
            }
        }
           
    }

    public function restore(Request $request,$id){
            if(News::restoreArticle($id)){
                if($request->ajax()){
                    return json_encode([
                        'msg'=>'Noticia Restaurada Com Sucesso',
                        'status'=>'SUCCESS'
                    ]);
                }
                else{
                    return redirect('/news')->with('flash-success','Noticia Restaurada com Sucesso');
                }
            }
        else{
            if($request->ajax()){
                return json_encode([
                    'msg'=>'Ocorreu um erro ao tentar restaurar a notícia',
                    'status'=>'ERROR'
                ]);
            }
            else{
                return redirect('/news')->with('flash-error','Erro ao tentar restaurar Noticia');
            }
            
        }
    }

       
    public function search(Request $request)
    {
        $this->validate($request,['trashed'=>'required']);

        //array para seguir caminho para o Modelo,com associatovos referentes às colunas da tabela
        $data=[
            'title'=>$request->input('qtitle'),
            'created_at'=>$request->input('qdate'),
            'id_state'=>$request->input('qstate'),
            'trashed'=>$request->input('trashed')
        ];

        //array para preencher os dados de volta à view
        $search=[
            'qtitle'=>$request->input('qtitle'),
            'qdate'=>$request->input('qdate'),
            'qstate'=>$request->input('qstate'),
            'trashed'=>$request->input('trashed')
        ];

       if($request->ajax()){
            $data['isajx']=1; //parametro para indicar se e um pedido ajax   
            $news=News::searchNews($data);
            return $news;
        }
        else{
            $news=News::searchNews($data);
            $states=States::All();
            $news->title="Resultados Da Pesquisa";
            return view('home',compact('news'),compact('states'),compact('search'));
        }  
    }
}

resources/views/news/create.blade.php
@extends('layouts.app')
@section('content')
    
<div class="container">
        <script src="{{asset('js/article_ajx.js')}}"></script>
    <h2>Criar Artigo</h2>
    <a onclick=" window.history.back();"><button class="btn btn-primary"><i class="fas fa-chevron-left"></i>&nbsp; Voltar Atrás</button></a>
    <div class="mt-3" id="msg"></div>
    <form method="POST" id="formcreate" action="{{route('news.store')}}">
    @csrf
    <label for="title">Titulo:</label>
    <input type="text" class="form-control" required id="title" name="title"><br>
    <label for="content">Conteudo: </label>
    <textarea class="form-control" required id="content" name="content"></textarea>
    <label>Estado:</label>
    <select class="form-control" required id="state" name="state">
    @if(count($states))
        @foreach($states as $state)
            <option value="{{$state->id}}">{{$state->description}}</option>
         @endforeach
    @else
        <option value="1">Publicado</option>
        <option value="2">Não Publicado</option>
    @endif
    </select><br>
    <button class="btn btn-primary" type="submit">Adicionar Noticia</button>
</form>
</div>
@endsection

resources/views/news/edit.blade.php
@extends('layouts.app')
@section('content')
    
<div class="container">
        <script src="{{asset('js/article_ajx.js')}}"></script>
        <h2>Editar Artigo</h2>
        <a onclick=" window.history.back();"><button class="btn btn-primary"><i class="fas fa-chevron-left"></i>&nbsp; Voltar Atrás</button></a>
        <div class="mt-3" id="msg"></div>
        @if(isset($article))
  
<form method="POST" id="formedit" action="{{route('news.update',$article->id)}}">
        {{method_field('PUT')}}
    @csrf
    <label for="title">Titulo:</label>
<input type="text" class="form-control" minlength="3" maxlength="50" value="{{$article->title}}" id="title" name="title"><br>
    <label for="content">Conteudo: </label>
<textarea class="form-control" id="content" name="content" minlength="20" maxlength="200">{{$article->content}}</textarea>
    <label>Estado:</label>
    <select class="form-control" id="state" name="state">
    @if(count($states))
        @foreach($states as $state)
            <option value="{{$state->id}}"@if($article->id_state ==$state->id) selected AQUI @endif>{{$state->description}}</option>
        @endforeach
    @else
        <option value="1">Publicado</option>
        <option value="2">Não Publicado</option>
    @endif  
    </select><br>
    <button class="btn btn-primary" type="submit">Guardar Alterações</button>
</form>
@else
<h1>Artigo Não encontrado!</h1>
@endif

</div>
@endsection

resources/views/news/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <a onclick=" window.history.back();"><button class="btn btn-primary"><i class="fas fa-chevron-left"></i>&nbsp; Voltar Atrás</button></a>
<h2>{{$article->title}}</h2>
<small>Publicado a {{$article->created_at->format('Y-m-d H:i:s')}} por {{$article->user->name}}</small><br>
<h5 style="display:inline">Estado:</h5> <h6 style="display:inline; @if($article->deleted_at!=NULL) text-decoration: line-through"@else" @endif>{{$article->state->description}}@if($article->deleted_at!=NULL)<h5 class="alert-danger">ARTIGO APAGADO</h5>@endif</h6>
<h2 class="mt-2">Conteudo:</h2>
<div class="container  mt-3">
<div class="font-weight-light">{!!$article->content!!}</div>
</div>
@endsection